project:
  type: website

website:
  title: "Thomas W. Bush"
  site-url: "https://thomasbush9.github.io/myblog/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: books/index.qmd
        text: Books
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/Thomasbush9
      - icon: file-person
        href: /cv/ThomasBush_CV.pdf
  search:
    location: navbar
    type: overlay
format:
  html:
    toc: true
    theme: 
      - cosmo
      - brand
    css: styles.css
    mainfont: "JetBrains Mono"
    monofont: "JetBrains Mono"
execute:
  freeze: auto
publish:
  method: gh-pages
resources:
  - cv/ThomasBush_CV.pdf


